### ISSUE TITLE
lambda-prolog - Base du projet

### ISSUE THREAD

**Issue by Vertmo** [grapa-central/2019-lambdaProlog#7]
Il faudrait mettre en place la base du projet assez rapidement (tout ce qui est système d'installation et de packaging clojure, résolution des dépendances, etc...). Je peux probablement m'en charger d'ici demain.
Il pourrait aussi être intéressant d'avoir un système de CI vu qu'on travail à beaucoup. Est-ce qu'il y-a des gens qui s'y connaissent en tests unitaires en clojure ? J'ai des vagues souvenirs du cours de L3 mais j'imagine qu'il y a des choses mieux qui se font ? L'idéal serait de pouvoir les intégrer avec GitHub action ou un système de CI externe qu'on peut brancher dans GitHub.

**Comment by Polybulle** [comment]
Manifestement, github propose des actions pour leiningen, qui est assez bien établi dans le monde clojure (de ce que j'ai compris). Par contre, clojure propose un gestion des tests et des dépendances intégrés, qu'on pourrait utiliser avec github avec un peu d'huile de coude.

https://github.com/actions/starter-workflows/blob/master/ci/clojure.yml
https://leiningen.org/
https://clojure.org/guides/deps_and_cli

**Comment by Vertmo** [comment]
Du coup c'est réglè par #9
