### ISSUE TITLE
lambda-prolog - Syntaxe et représentation des termes

### ISSUE THREAD

**Issue by Vertmo** [grapa-central/2019-lambdaProlog#8]
Une fois qu'on aura fait #7, il va falloir définir précisément la syntaxe (des lambda-termes en particulier), mais du "vernacular" lambda-prolog aussi. 
Il va aussi falloir réfléchir à la représentation des termes (en particulier, est-ce qu'on utilise des indices de De Bruijn, ou est-ce qu'on utilise des noms de variables ?, @Polybulle et @Jugst3r j'imagine que vous avez une opinion la-dessus ?)

**Comment by Polybulle** [comment]
Pour la représentation des termes, il faudrait à mon avis partir sur Locally Nameless (variable liées en De Bruijn, et libres = substituables en symbolique). Avec des symboles de constantes et les valeurs et types primitifs (mais ça c'est encore une autre histoire).
Pour l'algo d'Huet, se serais bien d'avoir des abstractions et applications à _n_ arguments pour manipuler les têtes des termes en forme normale. Pour l'évaluation et la substitution, peut être qu'on devra ajouter une construction de suspension/substitution explicite.
Donc, en gros (syntaxe Caml, navré)

```ocaml
type term =
  | bound of int
  | free of symbol
  | const of symbol
  | primitive of something
  | abstraction of int * term
  | application of term * (term list)
  | suspension of something_else
```

**Comment by Vertmo** [comment]
J'allais dire qu'on aurait pu définir un type somme séparé pour les termes en forme normale de tête, et puis je me suis souvenu qu'on faisait du clojure x) Du coup dans `abstraction of int * term` l'entier c'est l'arité de l'abstraction ?
Aussi j'ai un peu du mal à voir pourquoi `free` et `const` prennent un parametre similaire ?

**Comment by Vertmo** [comment]
Autre question : est-ce qu'on veut faire un parser, ou est-ce qu'on préfère déclarer les termes, clauses, ... a coup de macros clojure ? La deuxième solution me semble plus naturelle si le but est d'utiliser `clj-lprolog` comme bibliothèque pour `latte` et `deputy`, mais on peut aussi faire les deux j'imagine

**Comment by Polybulle** [comment]
1. en effet c'est confus (désolé): on a besoin soit de `const` soit de `primitive`, en plus de `free` pour les variables substituables. Pour l'unification, on peut se contenter de `const` sans problème
2. Coté syntaxe, ça parait en effet mieux de prendre en entrée du clojure. On pourrait avoir une syntaxe EDN et des macros de convenances. Avoir un parser devant ça me fait plus penser à du scheme qu'à du clojure.

**Comment by Vertmo** [comment]
Ca fait sens ^^ je vais commencer à m'en occuper, pour le moment je ne vais pas mettre de `const` comme ça on pourra décider collégialement de ce qu'on met dans le langage ^^

Oui c'est assez naturel effectivement. Je pense qu'il faut quand meme mettre un "parser" pour transformer des termes utilisateurs (i.e. avec variables nommées) en termes noyaux (i.e. avec indices de De Bruijn)

**EDIT**: Après reflexion il apparait que le plus logique est de mettre les constantes de la High Order Logic sur laquelle lambda prolog est basée, à savoir 
* Les constantes logiques: `forall`, `=>`
* Les constantes arithmétiques : `0`, `S`, `+`, `*`. Qu'en pensez vous ?
